import { log } from 'apify';
import { buildGeneratedQueries } from './input.js';
import { domainExcluded, hostnameFromUrl, safeUrl, uniq } from './utils.js';
export async function discoverUrls(input) {
  const candidates = [];
  for (const item of input.startUrls) candidates.push({ url: item.url, userData: { sourceType: 'startUrl', ...item.userData } });
  for (const lead of input.manualLeads) if (lead.website) candidates.push({ url: lead.website, userData: { sourceType: 'manualLead', manualLead: lead } });
  if (input.discoveryProvider && input.discoveryProvider !== 'none') { const queries = buildGeneratedQueries(input); log.info(`Discovery enabled with ${input.discoveryProvider}. Queries: ${queries.length}`); for (const query of queries) { const urls = await searchProvider(query, input); for (const url of urls) candidates.push({ url, userData: { sourceType: 'search', query } }); if (candidates.length >= input.maxResults * 2) break; } }
  const filtered = []; const seenHosts = new Set();
  for (const item of candidates) { const url = safeUrl(item.url); if (!url || domainExcluded(url, input.excludeDomains)) continue; const host = hostnameFromUrl(url); if (seenHosts.has(host)) continue; seenHosts.add(host); filtered.push({ url, userData: item.userData || {} }); if (filtered.length >= input.maxResults) break; }
  return filtered;
}
async function searchProvider(query, input) { if (input.discoveryProvider === 'serpapi') return serpApiSearch(query, input); if (input.discoveryProvider === 'googleCustomSearch') return googleCustomSearch(query, input); if (input.discoveryProvider === 'bing') return bingSearch(query, input); return []; }
async function serpApiSearch(query, input) { if (!input.serpApiKey) { log.warning('SerpApi selected but serpApiKey is missing.'); return []; } const url = new URL('https://serpapi.com/search.json'); url.searchParams.set('engine','google'); url.searchParams.set('q',query); url.searchParams.set('num',String(input.maxSearchResultsPerQuery)); url.searchParams.set('api_key',input.serpApiKey); const data = await fetchJson(url.href); return uniq((data.organic_results || []).map((item) => item.link)).slice(0, input.maxSearchResultsPerQuery); }
async function googleCustomSearch(query, input) { if (!input.googleApiKey || !input.googleCx) { log.warning('Google Custom Search selected but googleApiKey or googleCx is missing.'); return []; } const out=[]; let start=1; while (out.length < input.maxSearchResultsPerQuery) { const url = new URL('https://www.googleapis.com/customsearch/v1'); url.searchParams.set('key',input.googleApiKey); url.searchParams.set('cx',input.googleCx); url.searchParams.set('q',query); url.searchParams.set('num',String(Math.min(10, input.maxSearchResultsPerQuery-out.length))); url.searchParams.set('start',String(start)); const data = await fetchJson(url.href); out.push(...(data.items || []).map((item) => item.link)); if (!data.items?.length) break; start += data.items.length; if (start > 91) break; } return uniq(out).slice(0, input.maxSearchResultsPerQuery); }
async function bingSearch(query, input) { if (!input.bingApiKey) { log.warning('Bing selected but bingApiKey is missing.'); return []; } const url = new URL('https://api.bing.microsoft.com/v7.0/search'); url.searchParams.set('q',query); url.searchParams.set('count',String(input.maxSearchResultsPerQuery)); const response = await fetch(url.href,{ headers:{ 'Ocp-Apim-Subscription-Key': input.bingApiKey } }); if (!response.ok) { log.warning(`Bing search failed with ${response.status} for query: ${query}`); return []; } const data = await response.json(); return uniq((data.webPages?.value || []).map((item) => item.url)).slice(0, input.maxSearchResultsPerQuery); }
async function fetchJson(url) { const response = await fetch(url,{ headers:{ 'User-Agent':'Apify Lead Enrichment Actor/0.1','Accept':'application/json' } }); if (!response.ok) { log.warning(`Search API request failed: ${response.status} ${response.statusText}`); return {}; } return response.json(); }
