import { hostnameFromUrl, limitArray, normalizeWhitespace, textIncludesAny, uniq } from './utils.js';
const GENERIC_EMAIL_PREFIXES=/^(info|hello|contact|sales|support|office|admin|team|booking|bookings|reception|appointments|service|services|enquiry|enquiries|marketing|customerservice)$/i;
const CATEGORY_KEYWORDS=[['dentist',['dentist','dental','orthodont','implant','teeth whitening']],['clinic',['clinic','medical','doctor','patient','appointment','healthcare','pharmacy']],['law firm',['law firm','attorney','lawyer','legal','solicitor','barrister']],['roofing',['roofing','roof repair','gutter','siding']],['real estate',['real estate','property','homes for sale','realtor','estate agent']],['restaurant',['restaurant','menu','order online','reservation','takeaway','food delivery']],['salon',['salon','beauty','barber','spa','nails','haircut']],['hotel',['hotel','rooms','booking','reservation','guest house']],['solar',['solar','photovoltaic','pv system','renewable energy']],['saas',['saas','software','platform','api','cloud software']]];
export function extractPageSignals({ $, url, html = '', includePersonalEmails = false }) {
  const text=normalizeWhitespace($('body').text()); const lowerHtml=html.toLowerCase(); const links=$('a[href]').map((_,el)=>({href:String($(el).attr('href')||'').trim(),text:normalizeWhitespace($(el).text())})).get(); const jsonLd=parseJsonLd($); const structured=extractStructuredBusiness(jsonLd); const title=normalizeWhitespace($('title').first().text()); const h1=normalizeWhitespace($('h1').first().text()); const metaDescription=normalizeWhitespace($('meta[name="description"]').attr('content')||$('meta[property="og:description"]').attr('content')||''); const siteName=normalizeWhitespace($('meta[property="og:site_name"]').attr('content')||$('meta[name="application-name"]').attr('content')||structured.name||''); const category=inferCategory(`${title} ${h1} ${metaDescription} ${text}`);
  return { host:hostnameFromUrl(url), sourceUrl:url, businessName:pickBusinessName({structured,siteName,h1,title,host:hostnameFromUrl(url)}), title, metaDescription, category, emails:extractEmails(html,includePersonalEmails), phones:extractPhones(text,links), address:structured.address||'', city:structured.city||'', country:structured.country||'', socialLinks:extractSocialLinks(links), contactLinks:limitArray(links.filter((l)=>textIncludesAny(`${l.href} ${l.text}`,['contact','get in touch','call us','email us','contact us','quote','free estimate'])).map((l)=>l.href),10), signals:{ hasContactForm:$('form').length>0 && $('input[type="email"], input[name*="email" i], textarea').length>0, hasPhoneLink:links.some((l)=>l.href.toLowerCase().startsWith('tel:')), hasEmailLink:links.some((l)=>l.href.toLowerCase().startsWith('mailto:')), hasWhatsApp:lowerHtml.includes('wa.me/')||lowerHtml.includes('api.whatsapp.com')||lowerHtml.includes('whatsapp'), hasGoogleMaps:lowerHtml.includes('maps.google')||lowerHtml.includes('google.com/maps'), hasBooking:textIncludesAny(`${text} ${links.map((l)=>l.href).join(' ')}`,['book','appointment','schedule','reservation','reserve','calendly','acuity']), hasEcommerce:textIncludesAny(`${text} ${lowerHtml}`,['cart','checkout','shopify','woocommerce','order now','buy now']), hasSchema:jsonLd.length>0||lowerHtml.includes('schema.org'), hasPrivacyPolicy:lowerHtml.includes('privacy policy'), hasTestimonials:textIncludesAny(text,['testimonial','reviews','what our clients say','case studies']), hasNewsletter:textIncludesAny(text,['newsletter','subscribe']) }, technologies:detectTechnologies(lowerHtml), pageEvidence:{title,h1,metaDescription,pagesSignals:{forms:$('form').length,emailInputs:$('input[type="email"], input[name*="email" i]').length,totalLinks:links.length}} };
}
function parseJsonLd($){const out=[];$('script[type="application/ld+json"]').each((_,el)=>{try{const p=JSON.parse($(el).text()); if(Array.isArray(p))out.push(...p); else if(p?.['@graph'])out.push(...p['@graph']); else if(p)out.push(p);}catch{}}); return out;}
function extractStructuredBusiness(items=[]){const b=items.find((item)=>{const t=Array.isArray(item['@type'])?item['@type'].join(' '):item['@type']; return /Organization|LocalBusiness|Restaurant|Dentist|MedicalBusiness|LegalService|RealEstateAgent/i.test(t||'');})||{}; const a=typeof b.address==='object'?b.address:{}; return {name:b.name||'',address:normalizeWhitespace([a.streetAddress,a.addressLocality,a.addressRegion,a.postalCode,a.addressCountry].filter(Boolean).join(', ')),city:a.addressLocality||'',country:a.addressCountry||''};}
function pickBusinessName({structured,siteName,h1,title,host}){const c=[structured.name,siteName,h1,title].map(normalizeWhitespace).filter(Boolean).filter((v)=>!/^(home|welcome|index)$/i.test(v)); const picked=c[0]||host||''; return picked.replace(/\s+\|.*$/,'').replace(/\s+-\s+.*$/,'').slice(0,120);}
function extractEmails(html,includePersonalEmails){const emails=[]; const decoded=html.replace(/%40/g,'@').replace(/\s*\[at\]\s*/gi,'@').replace(/\s*\(at\)\s*/gi,'@'); for(const match of decoded.match(/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/g)||[]){const email=match.toLowerCase().replace(/[.,;:)]$/,''); if(email.includes('example.')||email.includes('domain.com'))continue; if(!includePersonalEmails && !GENERIC_EMAIL_PREFIXES.test(email.split('@')[0]))continue; emails.push(email);} return limitArray(uniq(emails),8);}
function extractPhones(text,links){const phones=[]; for(const link of links) if(link.href.toLowerCase().startsWith('tel:')) phones.push(link.href.replace(/^tel:/i,'')); for(const match of text.match(/(?:\+?\d[\d().\-\s]{7,}\d)/g)||[]){const digits=match.replace(/\D/g,''); if(digits.length>=8&&digits.length<=16)phones.push(match);} return limitArray(uniq(phones.map((p)=>normalizeWhitespace(p))),8);}
function extractSocialLinks(links){const socialHosts=['facebook.com','instagram.com','linkedin.com','youtube.com','tiktok.com','x.com','twitter.com']; const out={}; for(const link of links){let host=''; try{host=new URL(link.href,'https://placeholder.local').hostname.replace(/^www\./,'');}catch{continue;} const matched=socialHosts.find((s)=>host===s||host.endsWith(`.${s}`)); if(matched&&!out[matched])out[matched]=link.href;} return out;}
function inferCategory(text){const n=text.toLowerCase(); const m=CATEGORY_KEYWORDS.find(([,words])=>words.some((w)=>n.includes(w))); return m?m[0]:'';}
function detectTechnologies(lowerHtml){const checks=[['WordPress',['wp-content','wp-includes']],['Shopify',['cdn.shopify.com','shopify.theme']],['WooCommerce',['woocommerce']],['Wix',['wixstatic.com','wix.com']],['Squarespace',['squarespace.com']],['Webflow',['webflow']],['Google Analytics',['google-analytics.com','gtag(']],['Google Tag Manager',['googletagmanager.com']],['Meta Pixel',['connect.facebook.net','fbq(']],['HubSpot',['hubspot']],['Calendly',['calendly.com']]]; return checks.filter(([,needles])=>needles.some((n)=>lowerHtml.includes(n))).map(([name])=>name);}
