import { safeUrl, toStartUrlObjects } from './utils.js';
const DEFAULT_EXCLUDE_DOMAINS = ['facebook.com','instagram.com','linkedin.com','youtube.com','twitter.com','x.com','tiktok.com','yelp.com','tripadvisor.com','yellowpages.com'];
const DEFAULT_NICHES = ['dentists','law firms','roofing companies','real estate agents','clinics'];
const DEFAULT_COUNTRIES = ['United States','United Kingdom','Canada','Australia'];
export function normalizeInput(raw = {}) {
  const input = { startUrls: toStartUrlObjects(raw.startUrls || []), manualLeads: Array.isArray(raw.manualLeads) ? raw.manualLeads : [], discoveryProvider: raw.discoveryProvider || 'none', searchQueries: Array.isArray(raw.searchQueries) ? raw.searchQueries.filter(Boolean).map(String) : [], countries: Array.isArray(raw.countries) && raw.countries.length ? raw.countries.map(String) : DEFAULT_COUNTRIES, niches: Array.isArray(raw.niches) && raw.niches.length ? raw.niches.map(String) : DEFAULT_NICHES, maxSearchResultsPerQuery: num(raw.maxSearchResultsPerQuery,1,100,10), maxResults: num(raw.maxResults,1,10000,100), maxPagesPerWebsite: num(raw.maxPagesPerWebsite,1,25,3), maxConcurrency: num(raw.maxConcurrency,1,100,10), includePersonalEmails: Boolean(raw.includePersonalEmails), outreachLanguage: raw.outreachLanguage || 'English', outreachTone: raw.outreachTone || 'consultative', serpApiKey: raw.serpApiKey || process.env.SERPAPI_KEY || '', googleApiKey: raw.googleApiKey || process.env.GOOGLE_API_KEY || '', googleCx: raw.googleCx || process.env.GOOGLE_CX || '', bingApiKey: raw.bingApiKey || process.env.BING_API_KEY || '', excludeDomains: Array.isArray(raw.excludeDomains) ? raw.excludeDomains.map(String) : DEFAULT_EXCLUDE_DOMAINS, proxyConfiguration: raw.proxyConfiguration || { useApifyProxy: false }, debug: Boolean(raw.debug) };
  input.manualLeads = input.manualLeads.map((lead, index) => ({ businessName: lead.businessName || lead.name || '', website: safeUrl(lead.website || lead.url || ''), category: lead.category || lead.niche || '', city: lead.city || '', country: lead.country || '', phone: lead.phone || '', email: lead.email || '', notes: lead.notes || '', sourceType: 'manual', manualIndex: index }));
  return input;
}
function num(v, min, max, fallback) { const n = Number(v || fallback); return Number.isFinite(n) ? Math.max(min, Math.min(max, Math.round(n))) : fallback; }
export function buildGeneratedQueries(input) { if (input.searchQueries.length) return input.searchQueries; const queries = []; for (const country of input.countries) for (const niche of input.niches) { queries.push(`${niche} in ${country} contact website`); if (queries.length >= 50) return queries; } return queries; }
