import { Actor, log } from 'apify';
import { CheerioCrawler } from 'crawlee';
import { discoverUrls } from './discovery.js';
import { createEmptyAggregate, finalizeLead, mergeSignals } from './enrich.js';
import { extractPageSignals } from './extract.js';
import { normalizeInput } from './input.js';
import { currentIso, hostnameFromUrl, safeUrl, textIncludesAny } from './utils.js';
await Actor.init();
const startedAt=currentIso(); const rawInput=await Actor.getInput()||{}; const input=normalizeInput(rawInput); const aggregates=new Map();
try{
  await Actor.setStatusMessage('Preparing lead discovery inputs...'); const discoveredUrls=await discoverUrls(input);
  for(const lead of input.manualLeads){ if(!lead.website){ const key=`manual:${lead.manualIndex}`; aggregates.set(key, createEmptyAggregate({website:'',manualLead:lead,sourceType:'manualLeadNoWebsite'})); } }
  if(!discoveredUrls.length&&!aggregates.size)log.warning('No URLs or manual leads supplied. Provide startUrls/manualLeads or enable a discovery provider with API keys.');
  const proxyConfiguration=input.proxyConfiguration?.useApifyProxy ? await Actor.createProxyConfiguration(input.proxyConfiguration) : undefined;
  const perHostPageCount=new Map();
  const crawler=new CheerioCrawler({ proxyConfiguration, maxConcurrency:input.maxConcurrency, maxRequestsPerCrawl:Math.max(1,discoveredUrls.length*input.maxPagesPerWebsite), maxRequestRetries:2, requestHandlerTimeoutSecs:60, async requestHandler({request,$,body,enqueueLinks,response}){ const loadedUrl=request.loadedUrl||request.url; const host=hostnameFromUrl(loadedUrl); const currentCount=perHostPageCount.get(host)||0; perHostPageCount.set(host,currentCount+1); await Actor.setStatusMessage(`Analyzing ${host} (${aggregates.size} leads found so far)`); const manualLead=request.userData?.manualLead||{}; const key=host||loadedUrl; const aggregate=aggregates.get(key)||createEmptyAggregate({website:safeUrl(`https://${host}`)||loadedUrl,manualLead,sourceType:request.userData?.sourceType||'crawl'}); const pageSignals=extractPageSignals({$,url:loadedUrl,html:typeof body==='string'?body:body?.toString?.()||'',includePersonalEmails:input.includePersonalEmails}); if(response?.statusCode)pageSignals.httpStatus=response.statusCode; mergeSignals(aggregate,pageSignals,request.userData); aggregates.set(key,aggregate); if((perHostPageCount.get(host)||0)<input.maxPagesPerWebsite){ await enqueueLinks({ strategy:'same-hostname', transformRequestFunction:(req)=>{ const u=req.url.toLowerCase(); const relevant=textIncludesAny(u,['contact','about','service','services','pricing','book','appointment','menu','order','reservation','quote','location','locations','team','property','properties','case-study','reviews','testimonials']); if(!relevant)return false; req.userData={...request.userData,depth:Number(request.userData?.depth||0)+1}; return req; } }); } }, failedRequestHandler({request,error}){ log.warning(`Request failed: ${request.url} - ${error?.message||error}`); } });
  if(discoveredUrls.length)await crawler.run(discoveredUrls);
  await Actor.setStatusMessage('Scoring and exporting leads...'); const outputLeads=[...aggregates.values()].map((a)=>finalizeLead(a,input)).sort((a,b)=>b.leadScore-a.leadScore).slice(0,input.maxResults); for(const lead of outputLeads)await Actor.pushData(lead);
  const summary={actor:'global-ai-b2b-lead-enrichment',startedAt,finishedAt:currentIso(),discoveredUrls:discoveredUrls.length,leadsExported:outputLeads.length,highPriorityLeads:outputLeads.filter((l)=>l.priority==='high').length,mediumPriorityLeads:outputLeads.filter((l)=>l.priority==='medium').length,discoveryProvider:input.discoveryProvider,notes:['Dataset contains one row per enriched business lead.','Use startUrls/manualLeads for the most deterministic results.','Use discoveryProvider only with API keys and in compliance with search provider terms.']}; await Actor.setValue('OUTPUT',summary); await Actor.setStatusMessage(`Finished. Exported ${outputLeads.length} leads.`);
}catch(error){ log.exception(error,'Actor failed'); await Actor.setValue('OUTPUT',{actor:'global-ai-b2b-lead-enrichment',startedAt,finishedAt:currentIso(),error:error.message}); throw error; } finally { await Actor.exit(); }
